train:
  dataset:
    repo_id: "flexiv/teleop_dataset_20260619_104810_exclude_14_15_video"
    root: "/home/deepcybo/.cache/huggingface/lerobot/flexiv/teleop_dataset_20260619_104810_exclude_14_15_video"

  env:

  policy:
    type: "diffusion"
    device: "cuda"
    repo_id: "flexiv/diffusion_teleop_20260619_104810_exclude_14_15"
    push_to_hub: false  # 禁用模型推送

  output_dir: "outputs/flexiv/diffusion_teleop_20260619_104810_exclude_14_15"
  job_name: "diffusion_flexiv_teleop_20260619_104810_exclude_14_15"

  resume: false
  seed: 1000
  # Number of workers for the dataloader.
  num_workers: 0
  batch_size: 32
  steps: 10_000
  eval_freq: 0
  log_freq: 1
  save_checkpoint: True
  # Checkpoint is saved every `save_freq` training iterations and after the last training step.
  save_freq: 1_000
  use_policy_training_preset: True

  eval: 
    n_episodes: 10
    batch_size: 8

  wandb: 
    enable: True
    disable_artifact: True
    project: "lerobot"
    # entity: "your-wandb-username"  # 改为您的 WandB 用户名，或注释掉使用默认
    # notes: "训练备注"
    # run_id: "自定义运行ID"
    mode: "online"  # Allowed values: 'online', 'offline' 'disabled'. Defaults to 'online"
